.PHONY: clean All

All:
	@echo "----------Building project:[ codelite_test1 - Debug ]----------"
	@cd "codelite_test1" && "$(MAKE)" -f  "codelite_test1.mk"
clean:
	@echo "----------Cleaning project:[ codelite_test1 - Debug ]----------"
	@cd "codelite_test1" && "$(MAKE)" -f  "codelite_test1.mk" clean
