.PHONY: clean All

All:
	@echo "----------Building project:[ test7 - Debug ]----------"
	@cd "test7" && "$(MAKE)" -f  "test7.mk"
clean:
	@echo "----------Cleaning project:[ test7 - Debug ]----------"
	@cd "test7" && "$(MAKE)" -f  "test7.mk" clean
